server:
  port: 8989

spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  datasource:
    username: root
    password: 1515
    url: jdbc:mysql://localhost:3306/flyway?useSSL=false&autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
#    jdbc-url: jdbc:mysql://localhost:3306/flyway?useSSL=false&autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
#    driver-class-name: com.mysql.cj.jdbc.Driver